package ch.uzh.ifi.seal.soprafs20.GameLogic;

public class TextFile {
    public String words = "Alcatraz\n" +
            "Smoke\n" +
            "Hazelnut\n" +
            "Diamond\n" +
            "Rose\n" +
            "\n" +
            "Puppet\n" +
            "Game\n" +
            "Vegas\n" +
            "Chest\n" +
            "Airplane\n" +
            "\n" +
            "Cord\n" +
            "Australia\n" +
            "Castle\n" +
            "Guard\n" +
            "Sheep\n" +
            "\n" +
            "Fleece\n" +
            "Mouse\n" +
            "Chain\n" +
            "Farm\n" +
            "Belgium\n" +
            "\n" +
            "Pepper\n" +
            "Triangle\n" +
            "Doll\n" +
            "Italy\n" +
            "Stage\n" +
            "\n" +
            "Heart\n" +
            "Moscow\n" +
            "Billiards\n" +
            "Unicorn\n" +
            "Orange\n" +
            "\n" +
            "Tokyo\n" +
            "Heel\n" +
            "Chicken\n" +
            "Helicopter\n" +
            "Officer\n" +
            "\n" +
            "Melon\n" +
            "Anchor\n" +
            "Israel\n" +
            "Cactus\n" +
            "Tennis\n" +
            "\n" +
            "France\n" +
            "Moon\n" +
            "Canteen\n" +
            "Emperor penguin\n" +
            "Tool\n" +
            "\n" +
            "Brain\n" +
            "Mask\n" +
            "Concert\n" +
            "Troy\n" +
            "Shark\n" +
            "\n" +
            "Music\n" +
            "Neck\n" +
            "America\n" +
            "Coffee\n" +
            "Fever\n" +
            "\n" +
            "Barbie\n" +
            "Chocolate\n" +
            "Snow\n" +
            "Tie\n" +
            "Wind\n" +
            "\n" +
            "Thought\n" +
            "Frankenstein\n" +
            "Beam\n" +
            "Accent\n" +
            "Shower\n" +
            "\n" +
            "Ladybird\n" +
            "Mustard\n" +
            "Sherlock\n" +
            "Bottle\n" +
            "Virus\n" +
            "\n" +
            "Poison\n" +
            "Star\n" +
            "Wolf\n" +
            "Lena\n" +
            "Birthday\n" +
            "\n" +
            "Baker\n" +
            "Perfume\n" +
            "Flame\n" +
            "Zombie\n" +
            "Joker\n" +
            "\n" +
            "Buffy\n" +
            "Volcano\n" +
            "Passion\n" +
            "Cock\n" +
            "Electricity\n" +
            "\n" +
            "Genius\n" +
            "Dracula\n" +
            "Lion\n" +
            "Sock\n" +
            "Friday\n" +
            "\n" +
            "Pirate\n" +
            "Holidays\n" +
            "Fairy\n" +
            "Magnet\n" +
            "Fork\n" +
            "\n" +
            "Syrup\n" +
            "Forest\n" +
            "Scale\n" +
            "Zeus\n" +
            "Cockroach\n" +
            "\n" +
            "Dinosaur\n" +
            "Yellow\n" +
            "Mushroom\n" +
            "Pigeon\n" +
            "Pikachu\n" +
            "\n" +
            "Asterix\n" +
            "Robots\n" +
            "Comedy\n" +
            "Language\n" +
            "Hairdresser\n" +
            "\n" +
            "Cocktail\n" +
            "Mario\n" +
            "Cork\n" +
            "Violin\n" +
            "Peach\n" +
            "\n" +
            "Fox\n" +
            "Police\n" +
            "Simpson\n" +
            "Donut\n" +
            "Newspaper\n" +
            "\n" +
            "Mountains\n" +
            "Peanut\n" +
            "Light bulb\n" +
            "Jedi\n" +
            "Chili\n" +
            "\n" +
            "Sombrero\n" +
            "Cloverleaf\n" +
            "Button\n" +
            "Cheese\n" +
            "Chewbacca\n" +
            "\n" +
            "Revolver\n" +
            "Doctor\n" +
            "Strawberry\n" +
            "Nuclear power\n" +
            "Lottery\n" +
            "\n" +
            "Cemetery\n" +
            "Cupid\n" +
            "Umbrella\n" +
            "Jump\n" +
            "Root\n" +
            "\n" +
            "Treasure\n" +
            "Pilot\n" +
            "Mickey\n" +
            "Sewerage\n" +
            "Galaxy\n" +
            "\n" +
            "Moustache\n" +
            "Bubble\n" +
            "Chain\n" +
            "Strong\n" +
            "Cookie\n" +
            "\n" +
            "Croissant\n" +
            "Spirit\n" +
            "Straw\n" +
            "Nail\n" +
            "Potter\n" +
            "\n" +
            "Darwin\n" +
            "Tomato\n" +
            "Parachute\n" +
            "Cannon\n" +
            "Binoculars\n" +
            "\n" +
            "Fata morgana\n" +
            "Ramses\n" +
            "Fire\n" +
            "Intersection\n" +
            "Princess\n" +
            "\n" +
            "Spaceship\n" +
            "Bowling\n" +
            "Churchill\n" +
            "Aries\n" +
            "Spy\n" +
            "\n" +
            "Olympics\n" +
            "Climbing\n" +
            "Lawyer\n" +
            "Tolkien\n" +
            "River\n" +
            "\n" +
            "Carpet\n" +
            "Pony\n" +
            "Crown\n" +
            "New\n" +
            "Tarantino\n" +
            "\n" +
            "Heino\n" +
            "Ninja\n" +
            "Duvet\n" +
            "Hunter\n" +
            "Vegetables\n" +
            "\n" +
            "Cave\n" +
            "Hans\n" +
            "Casino\n" +
            "Candy\n" +
            "Fountain\n" +
            "\n" +
            "Light\n" +
            "Sofa\n" +
            "Mozart\n" +
            "Ring\n" +
            "Pizza\n" +
            "\n" +
            "Picture\n" +
            "Fire department\n" +
            "Glass\n" +
            "Meatball\n" +
            "Greece\n" +
            "\n" +
            "Tradition\n" +
            "Snake\n" +
            "Trophy\n" +
            "Picasso\n" +
            "Clock\n" +
            "\n" +
            "Pyre\n" +
            "Wizard\n" +
            "Hockey\n" +
            "Banana\n" +
            "Helene\n" +
            "\n" +
            "Caesar\n" +
            "Noodle\n" +
            "Hat\n" +
            "Dentist\n" +
            "Wheat\n" +
            "\n" +
            "Mussel\n" +
            "Shakespeare\n" +
            "Giant\n" +
            "Foam\n" +
            "Cellar\n" +
            "\n" +
            "Knives\n" +
            "Pillows\n" +
            "Armstrong\n" +
            "Sword\n" +
            "Flight\n" +
            "\n" +
            "Ticket\n" +
            "Penguin\n" +
            "Cell\n" +
            "Gandhi\n" +
            "Oasis\n" +
            "\n" +
            "Crocodile\n" +
            "Jewellery\n" +
            "Subway\n" +
            "Glasses\n" +
            "Falco\n" +
            "\n" +
            "Jackson\n" +
            "Cigarette\n" +
            "Bracelet\n" +
            "Weather forecast\n" +
            "Tower\n" +
            "\n" +
            "Tattoo\n" +
            "Spielberg\n" +
            "Apple\n" +
            "Mermaid\n" +
            "Boxes\n" +
            "\n" +
            "Dwarf\n" +
            "Circus\n" +
            "Elvis\n" +
            "Lawn mower\n" +
            "Stone\n" +
            "\n" +
            "Train\n" +
            "Sardine\n" +
            "Piece\n" +
            "Cleopatra\n" +
            "Window\n" +
            "\n" +
            "Pomegranate\n" +
            "Filling\n" +
            "Brush\n" +
            "Pig\n" +
            "Avicii\n" +
            "\n" +
            "Slipper\n" +
            "Sheet\n" +
            "Puma\n" +
            "Revolution\n" +
            "Sahara\n" +
            "\n" +
            "Knight\n" +
            "Peace\n" +
            "Flower\n" +
            "Switzerland\n" +
            "Calendar\n" +
            "\n" +
            "Schnitzel\n" +
            "Canada\n" +
            "Zoo\n" +
            "Whistle\n" +
            "Book";

    public String getWords() {
        return this.words;
    }
}
